### ISSUE TITLE
Very old version of cobe brain doesn't load

### ISSUE THREAD

**Issue by avinson** [pteichman/cobe#25]
So.. I must have had a really old cobe. Not sure what version but I'd like to get the data out of it as it's reasonable important to me. Back when it was called "cobe.store" instead of .brain. Error is below. Any tips? Thanks!

```sqlite3.OperationalError: no such table: info```

**Comment by pteichman** [comment]
@avinson Did you manage to get what you need out of it?

**Comment by avinson** [comment]
Going to retrain from some logs I got from a friend so I think I'm good. Thanks!

**Comment by pteichman** [comment]
Nice. My strategy in cobe's successor (fate) has been to do away with the database altogether: it's fast enough to train from scratch on start, so it wants text files with one line per trained sentence. Don't lose those logs. :)
